### ISSUE TITLE
working with negative number

### ISSUE THREAD

**Issue by wyvernnot** [ThomWright/format-si-prefix#1]
format-si-prefix@0.3.1

`require("format-si-prefix").formatSI(-10000000000)` will return `-1e+34y` ,

Is it by design? actually I'm expecting `-10G`

**Comment by ThomWright** [comment]
`-10G` would seem sensible! Looking at my tests it seems I didn't test any negative numbers (how embarrassing).

I'll have a look this weekend. Thanks!
