### ISSUE TITLE
Getting error Could not find module `format-si-prefix` imported

### ISSUE THREAD

**Issue by pRatikSathaye** [ThomWright/format-si-prefix#2]
I am creating an ember application.
I have installed this library using **npm install format-si-prefix**.
Then I used 
`import {formatSI} from 'format-si-prefix'`.

But giving me **Could not find module `format-si-prefix` error.**

Can anybody help on this?

**Comment by ThomWright** [comment]
Could you give me some more information on your setup, such as:

- NodeJS version
- any transpilers such as Babel (version and settings)
- anything else you think might be relevant

Thanks
